publicSourceURLs:
  - "https://raw.githubusercontent.com/proabiral/Fresh-Resolvers/refs/heads/master/resolvers.txt"
  - "https://raw.githubusercontent.com/trickest/resolvers/refs/heads/main/resolvers.txt"
  - "https://raw.githubusercontent.com/janmasarik/resolvers/refs/heads/master/resolvers.txt"
# - "https://raw.githubusercontent.com/blechschmidt/massdns/refs/heads/master/lists/resolvers.txt"

trustedSourceURLs:
  - "https://raw.githubusercontent.com/trickest/resolvers/refs/heads/main/resolvers-trusted.txt"
